/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oj;
import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author manohar
 */
public class Homepage extends javax.swing.JFrame implements Serializable{

    private String username, password, email;
    int ok;
   public static  ObjectOutputStream oos ;
  public static    ObjectInputStream ois ;
    boolean flag=true,flag2=true;
    
public  static Client socket;
    public Homepage() throws IOException {
        initComponents();
        //homepane.setBackground(Color.red);
    //   ImageIcon icon = new ImageIcon("/home/manohar/Desktop/bits.jpg"); 
      
//Logo.setIcon(icon);
       //homepane.drawImage();
       createsocket();
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Logintab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Homepanel = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        Loginp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsernameTextfieldLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jPasswordFieldLogin = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        IncorrectPassword = new javax.swing.JLabel();
        jCheckBox = new javax.swing.JCheckBox();
        Registerp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RegisterUsernamei = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EmailRegister = new javax.swing.JTextField();
        Registerbutton = new javax.swing.JButton();
        jPasswordFieldRegister = new javax.swing.JPasswordField();
        Userexistslabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Judge");

        Logintab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(66, 200, 245));

        jLabel16.setBackground(new java.awt.Color(72, 71, 48));
        jLabel16.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(225, 196, 50));

        jLabel7.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(168, 132, 80));

        Homepanel.setEditable(false);
        Homepanel.setColumns(20);
        Homepanel.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        Homepanel.setRows(5);
        Homepanel.setText("~The BitsPlease Online Judge is a project that is being \n  developed to enable the enthusiastic coders to practice \n  and improve their coding ability. \n~The main goal of the project is to provide \n  programming practice and knowledge sharing.\n~Solve the available problems using C, C++ competing with \n  other users.\n~As a challengee, improve your ranking, solving as many \n  problems as possible and tunning your source code to run \n  fast.");
        Homepanel.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(Homepanel);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/oj.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        Logintab.addTab("Home", jPanel1);

        Loginp.setBackground(new java.awt.Color(252, 162, 73));
        Loginp.setForeground(new java.awt.Color(80, 170, 200));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setText("Username :");

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel2.setText("Password :");

        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/submit.png"))); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        jCheckBox.setText("Remember me");
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginpLayout = new javax.swing.GroupLayout(Loginp);
        Loginp.setLayout(LoginpLayout);
        LoginpLayout.setHorizontalGroup(
            LoginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginpLayout.createSequentialGroup()
                        .addComponent(IncorrectPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
            .addGroup(LoginpLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(LoginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(LoginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox)
                    .addGroup(LoginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LoginButton)
                        .addComponent(UsernameTextfieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(jPasswordFieldLogin)))
                .addContainerGap(1358, Short.MAX_VALUE))
        );
        LoginpLayout.setVerticalGroup(
            LoginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginpLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(LoginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UsernameTextfieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox)
                .addGap(4, 4, 4)
                .addComponent(LoginButton)
                .addGap(27, 27, 27)
                .addComponent(IncorrectPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        Logintab.addTab("Login", Loginp);

        Registerp.setBackground(new java.awt.Color(204, 193, 150));

        jLabel3.setFont(new java.awt.Font("Cantarell", 2, 18)); // NOI18N
        jLabel3.setText("Username :");

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Cantarell", 2, 18)); // NOI18N
        jLabel5.setText("Email :");

        Registerbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_ok.png"))); // NOI18N
        Registerbutton.setText("Register");
        Registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterpLayout = new javax.swing.GroupLayout(Registerp);
        Registerp.setLayout(RegisterpLayout);
        RegisterpLayout.setHorizontalGroup(
            RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterpLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterpLayout.createSequentialGroup()
                        .addComponent(Userexistslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Registerbutton))
                    .addGroup(RegisterpLayout.createSequentialGroup()
                        .addGroup(RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(105, 105, 105)
                        .addGroup(RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterUsernamei, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1337, Short.MAX_VALUE))
        );
        RegisterpLayout.setVerticalGroup(
            RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterpLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RegisterUsernamei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(EmailRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(RegisterpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Userexistslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Registerbutton))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        Logintab.addTab("Register", Registerp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logintab, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logintab, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbuttonActionPerformed
        // TODO add your handling code here:
       
        username = RegisterUsernamei.getText();
      
        password = jPasswordFieldRegister.getText();
        email = EmailRegister.getText();
          password = jPasswordFieldRegister.getText();
        email = EmailRegister.getText();
         if(username.length()<6||username.length()>12)
             JOptionPane.showMessageDialog(this, "username must be between 6 to 12  characters");
         else if(password.length()<7)
             JOptionPane.showMessageDialog(this, "Password must be greater than 6 characters");
         else  if (!isValidEmailAddress(email)) {

            JOptionPane.showMessageDialog(this, "Please enter valid email address!!!");
        } else {
   
        try {
   Message msg=new Message();
    msg.email=email;
   msg.username=username;
   msg.password=password;
   msg.code=1;
   msg.status=0;
   socket.send(msg);
   System.out.print("Sending ok");
   msg=socket.receive();
   System.out.print("received ok");
   if(msg.status==1)
   {
      // JOptionPane.showMessageDialog(this,"Successfully Registered");
        new Profilepage(this,msg,socket).setVisible(true);
       
   }else
   {
       JOptionPane.showMessageDialog(this,"Already Registered!!");
   }
        } catch (Exception ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_RegisterbuttonActionPerformed
    }
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
          Message login=new Message();
          login.code=2;//code for login 
        login.username = UsernameTextfieldLogin.getText();
        login.password = jPasswordFieldLogin.getText();
        try {
            socket.send(login);
        } catch (Exception ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
int check;
        try {
            login=socket.receive();
        } catch (IOException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(login.loginstatus==1)
        {
               this.setVisible(false);
        new Profilepage(this,login,socket).setVisible(true);
        }else
        {
              JOptionPane.showMessageDialog(this,"Wrong Credentials!!");  
        }
        //JOptionPane.showMessageDialog(this, tt);
       if(!jCheckBox.isSelected())
        {
        
        UsernameTextfieldLogin.setText("");
        jPasswordFieldLogin.setText("");
        }
       /*
        if(tt.equals("Wrong"))
            JOptionPane.showMessageDialog(this,"Wrong Credentials!!");
        else{
            
        this.setVisible(false);
        new Profilepage(this).setVisible(true);
        }
        */
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBoxActionPerformed
    public boolean isValidEmailAddress(String email) {
        String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
        java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
        java.util.regex.Matcher m = p.matcher(email);
        return m.matches();
    }

    /**
    * @param args the command line arguments
    */
    
    public static  void createsocket() throws IOException
    {
         socket=new Client();
       socket.create();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Homepage().setVisible(true);
                    
                } catch (IOException ex) {
                    Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailRegister;
    private javax.swing.JTextArea Homepanel;
    private javax.swing.JLabel IncorrectPassword;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel Loginp;
    private javax.swing.JTabbedPane Logintab;
    private javax.swing.JTextField RegisterUsernamei;
    private javax.swing.JButton Registerbutton;
    private javax.swing.JPanel Registerp;
    private javax.swing.JLabel Userexistslabel;
    private javax.swing.JTextField UsernameTextfieldLogin;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    private javax.swing.JPasswordField jPasswordFieldRegister;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
